export const LOAD_BOOKMARK = "LOAD_BOOKMARK";
export const BOOKMARK_LOADED = "BOOKMARK_LOADED";

export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const EDIT_BOOKMARK = "EDIT_BOOKMARK";
export const DELETE_BOOKMARK = "DELETE_BOOKMARK";

export const ADD_BUTTON_ACTION = "ADD_BUTTON_ACTION";
export const HIDE_BUTTON_ACTION = "HIDE_BUTTON_ACTION";
export const EDIT_BUTTON_ACTION = "EDIT_BUTTON_ACTION";
export const BOOKMARK_ADD_EDIT_DONE = "BOOKMARK_ADD_EDIT_DONE";

export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";